### PR TITLE
Cleanup eclipse files that should not be in git

### PR DESCRIPTION
**Pull request by baerrach**

### CODE REVIEW

**Comment by phax** [comment]
Sorry man, but I have the Eclipse settings in all my projects. I need this because I'm working on different computers. Just ignore them :)

**Comment by baerrach** [comment]
You dont need em :) and they pollute git checkins.

m2e will regenerate them for you.

**Comment by phax** [comment]
Well not all the nifty little details. E.g. the project specific error/warning configuration, the used formatters, save actions, builders etc. Are you using a different IDE or what files get modified in your environment?

**Comment by baerrach** [comment]
I use Eclipse only.

It's a pain that every time you setup a new workspace you have to configure all those things. But you don't do that very often (at least not often enough that someone has bothered to fix that burden properly yet).

Even if you are working across multiple computers, its likely only 1 more computer.

But if you check that into git then any contributor will have to ignore those files when they send you a pull request.

I'm in the camp of ensuring that Eclipse Problem view is clean - no errors, no warnings.
The same with git - "git status" should report nothing left when I'm ready to push externally.
Its one more safety net to make sure I haven't forgotten to do something.

**Pull request closed without merging**
