### PR TITLE
Additional from functions for SchematronResourceXSLT

### PR DESCRIPTION
**Pull request by jw3**
This adds some static from functions that exist on the pure resource to the xslt resource.

Took a stab at some tests, let me know if something else would be useful.

The valid01.xslt was generated by the converter from the valid01.sch.

### CODE REVIEW

**Review by phax — APPROVED** [review]
Cool thanks :)

**Comment by phax** [comment]
New release is coming soon :)

**Comment by jw3** [comment]
Great, thanks :+1:

**Comment by phax** [comment]
Release 5.6.3 is out

**Pull request merged**
