### PR TITLE
m2e integration

### PR DESCRIPTION
**Pull request by baerrach**
Proper m2e integration (not just ignoring).

Happily change your schematron files and have them incrementally regenerated.

Won't break your eclipse build with the dreaded zombie nation invation of "Building workspace (Sleeping)" error message.

### CODE REVIEW

**Comment by baerrach** [comment]
I seem to have lost some of my notes.

But if you get org.slf4j.impl.StaticLoggerBinder errors then you need to add the "m2e - slf4j over logback logging (Optional)" Eclipse Plugin from your Eclipse update sites.

**Comment by phax** [comment]
Thank you very much for your effort! Are there additional build time requirements introduced through that (e.g. minimum Maven version)? Thanks!

**Comment by baerrach** [comment]
I dont believe so.

I'm using Eclipse Luna Service Release 2 (4.4.2) which has Maven 3.2.1 built in, and that seems to work.

I'm still tinkering with schematron so I haven't got it working on anything difficult yet.

**Comment by phax** [comment]
3.2.1 is fine :) thanks again

**Pull request merged**
